image:
  file: .gitpod.Dockerfile

tasks:
  - command: |
      echo ""
      echo "===================================================================="
      echo "Haskell installed. Use `ghci` to start GHC’s interactive environment"
      echo "===================================================================="
      echo ""
